version: '3.8'

services:
  telegram-service:
    build: .
    container_name: telegram-service
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./my_session.session:/app/my_session.session
      - ./session.session:/app/session.session
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - GIGACHAT_AUTH_KEY=${GIGACHAT_AUTH_KEY}
    env_file:
      - .env
    stdin_open: true
    tty: true
