services:
  telegram-service:
    build: .
    container_name: telegram-service
    restart: "no"
    volumes:
      - ./logs:/app/logs
      - ./sessions:/app/sessions
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - GIGACHAT_AUTH_KEY=${GIGACHAT_AUTH_KEY}
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: python tg_client.py
